name: Generate ASCII Artwork 2

on: push

# 1. All jobs run in parallel unless stated with needs syntax.
# 2. File created in one job is not accessible in another job. Hence, we need to upload and download artifacts 
# 3. Artifacts can be downloaded/seen on github actions

jobs:
    build_job_1:
        # Each job runs on their own VM
        runs-on: ubuntu-latest
        steps:
  
            - name: Install Cowsay Program
              run: sudo apt-get install cowsay -y

            - name: Execute Cowsay CMD
              run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt


            # File created in one job is not accessible in another job. Hence, we need to upload and download artifacts
            - name: Upload Dragon text file
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file
                path: dragon.txt

    test_job_2:

        # All jobs run in parallel unless stated with needs syntax.
        needs: build_job_1

        # Each job runs on their own VM
        runs-on: ubuntu-latest
        steps:
            - name: Download Dragon text file
              uses: actions/download-artifact@v4
              with:
                name: dragon-text-file  #This artifact name is taken from the name you assigned in job 1

            - name: Test File Exists
              run: grep -i "dragon" dragon.txt

    deploy_job_3:

        # 1. All jobs run in parallel unless stated with needs syntax. Can use array if needed [test_job_2, build_job_1]
        needs: test_job_2
        
        # Each job runs on their own VM
        runs-on: ubuntu-latest
        steps:
            - name: Download Dragon text file
              uses: actions/download-artifact@v4
              with:
                name: dragon-text-file  #This artifact name is taken from the name you assigned in job 1

            - name: Read File
              run: cat dragon.txt

            - name: Deploy
              run: echo Deploying ... .. .







        