name: Generate ASCII Artwork 2

on: push

# 2. File created in one job is not accessible in another job
jobs:
    build_job_1:
        # Each job runs on their own VM
        runs-on: ubuntu-latest
        steps:
 
            - name: Install Cowsay Program
              run: sudo apt-get install cowsay -y

            - name: Execute Cowsay CMD
              run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

            - name: Sleep for 30 seconds
              run: sleep 30

    test_job_2:

        # All jobs run in parallel unless stated with needs syntax.
        needs: build_job_1

        # Each job runs on their own VM
        runs-on: ubuntu-latest
        steps:
            - name: Sleep for 10 seconds
              run: sleep 10

            - name: Test File Exists
              run: grep -i "dragon" dragon.txt

    deploy_job_3:

        # 1. All jobs run in parallel unless stated with needs syntax. Can use array if needed [test_job_2, build_job_1]
        needs: test_job_2
        
        # Each job runs on their own VM
        runs-on: ubuntu-latest
        steps:
            - name: Read File
              run: cat dragon.txt

            - name: Deploy
              run: echo Deploying ... .. .







        