name: Testing
on:
    workflow_dispatch:

jobs:
    testing:
        # Must have at least 3 labels to match the self-hosted runner
        runs-on: [self-hosted, Windows, prod]
        steps:
            - name: Echo Content
              run: |
                echo Ok
                sleep 15s
