name: Testing
on:
    workflow_dispatch:
    push:

jobs:
    testing:
        runs-on: [self-hosted, Windows, prod]
        steps:
            - name: Echo Content
              run: |
                echo Ok
                sleep 15s
